### ISSUE TITLE
Breaking Change in non major version bump

### ISSUE THREAD

**Issue by turculaurentiu91** [apideck-libraries/php-sdk#44]
Hello,

Today I updated the php skd to latest `2.5.3` from `2.0` and I noticed that the `Apideck\Client\Model\GetEmployeesResponse::getData()` now returns `
EmployeeList[]` instead of `Employees[]` made by this commit https://github.com/apideck-libraries/php-sdk/commit/d2cf8fd36a56dc04a649fb10049e7c246c191ab1#

The new `EmployeeList` model doesn't allow to retrieve all the employee data, like `emails` or `addresses`. This should be a breaking change and it should bump the version to `3.0`.

Another related issue, if only the `id`, `first_name`, `last_name` is accessible via the `employeesAll` method, then the `fields` parameter that allows us to specify whan extra data **TO BE INCLUDED** is redundant.

From your API Documentation: https://developers.apideck.com/apis/hris/reference#operation/employeesAll

> fieldsstring or null
> The 'fields' parameter allows API users to specify the fields they want to include in the API response. If this parameter is not present, the API will return all available fields. If this parameter is present, only the fields specified in the comma-separated string will be included in the response. Nested properties can also be requested by using a dot notation.
> 
> Example: fields=name,email,addresses.city
> 
> In the example above, the response will only include the fields "name", "email" and "addresses.city". If any other fields are available, they will be excluded.

**Comment by thim81** [comment]
hi @turculaurentiu91 

We just released version 2.5.4 which reverts the reduced employee model (5 properties) and returns all Employee model 64 properties like before.

PHP SDK 2.5.2/2.5.3
![2023-09-29 at 13 41 11](https://github.com/apideck-io/unify/assets/952446/162ed2cb-fb4d-4357-8af9-9594061c5112)

PHP SDK 2.5.4
![2023-09-29 at 13 45 21](https://github.com/apideck-io/unify/assets/952446/ffee9238-fcfc-4ae6-aa77-742b622582de)

**Comment by thim81** [comment]
> Another related issue, if only the id, first_name, last_name is accessible via the employeesAll method, then the fields parameter that allows us to specify whan extra data TO BE INCLUDED is redundant.

The `fields` property is provided to reduce the returned properties, by default the API will return all the fields.
When you define a subset using "fields", the API will only return those fields.

![2023-09-29 at 13 49 58](https://github.com/apideck-libraries/php-sdk/assets/952446/51913b5d-eec9-4a8a-afbc-531e95c8e427)

**Comment by turculaurentiu91** [comment]
Thanks!
